### ISSUE TITLE
Schema gen tests

### ISSUE THREAD

**Issue by tonyketcham** [FlatbreadLabs/flatbread#17]
We should be able to verify that schema generation works as expected which will make changes that pass CI more trustless.

Within this, it's important to introduce basic sanity tests. We could perhaps leverage Playwright to do e2e tests across the whole Flatbread flow which will yield high coverage for minimal effort.

**Comment by odama626** [comment]
after https://github.com/tonyketcham/flatbread/pull/31 lands we should be able to do e2e testing with schema gen touching all but the apollo server code

**Comment by tonyketcham** [comment]
Added coverage for relational filtering in #35

As part of this ticket, we should add a single, dedicated `content` folder in the monorepo which supplies everything from internal framework integration (playground, integration examples) to schema gen tests

**Comment by tonyketcham** [comment]
After #51 goes in, it'll be much easier to consolidate down to one `content` folder.
