### ISSUE TITLE
importing @flatbread/core inside of a vite project fails

### ISSUE THREAD

**Issue by odama626** [FlatbreadLabs/flatbread#37]
importing @flatbread/core inside of a vite project on SSR fails because it imports the cjs file through `exports.require` and the require('lodash-es") blows up -- cannot import an esm package from cjs file

switching the `exports.require` to point to `dist/index.js` seems to solve the issue but I don't know if thats the right solution

**Comment by tonyketcham** [comment]
Thanks for finding - I had a feeling this would happen in CJS environments as the project leans on ESM-only deps. 

Will have to think on what the right approach is and maybe test across multiple integration environments such as Nuxt, Next.js, Vite SSR, Vite/SvelteKit, Astro, etc.

**Comment by tonyketcham** [comment]
Marking as resolved since we got rid of the CJS exports in core https://github.com/FlatbreadLabs/flatbread/releases/tag/v1.0.0-alpha.20
