### ISSUE TITLE
Ensure Windows & Mac machines can build Flatbread

### ISSUE THREAD

**Issue by tonyketcham** [FlatbreadLabs/flatbread#69]
We only test Windows and Mac support for end-users. It's important that we also know a change doesn't break platform support for development, as to not limit who can contribute to the project.

A PR including any needed fixes to get Flatbread compiling on Windows should also add Windows (and Mac) platform runners to the pipeline for the `build` stage

**Comment by odama626** [comment]
we can add linux to the list, it's what I use

**Comment by tonyketcham** [comment]
#85 got it working, #79 will leverage that to assert support in the pipeline
