### ISSUE TITLE
If Flatbread fails with an internal error, it should exit with failure state

### ISSUE THREAD

**Issue by tonyketcham** [FlatbreadLabs/flatbread#79]
### Example of issue

This pipeline job succeeds incorrectly even with an internal failure:
https://github.com/FlatbreadLabs/flatbread/runs/7621079297?check_suite_focus=true#step:7:167

**Comment by Sheharyar566** [comment]
I'm not sure why it didn't fail, but we might be able to use process "uncaught exception" listener to force a failure during the action 🤔
